Repository halo-sigs/awesome-halo, pull requests merged in 2022-12, with the labels that each got.

#9 feat: add plugin colorless
  README.md
Labels: lgtm, release-note-none, approved

#11 Add plugin pixabay
  README.md
Labels: lgtm, release-note-none, approved

#12 add theme-sakura and plugin-live2d
  README.md
Labels: lgtm, release-note-none, approved

#13 add theme-terminal
  README.md
Labels: lgtm, release-note, approved

#15 add halo-plugin-s3os
  README.md
Labels: lgtm, release-note-none, approved

#16 docs: move plugin-s3 to official plugin list
  README.md
Labels: lgtm, release-note-none, approved

#17 docs: add plugin-stackedit and plugin-bytemd
  README.md
Labels: lgtm, release-note-none, kind/documentation, approved
