Repository halo-sigs/awesome-halo, pull requests merged in 2022-10, with the labels that each got.

#1 add theme-hao
  README.md
Labels: lgtm, release-note-none

#2 add plugin-prismjs
  README.md
Labels: lgtm, do-not-merge/release-note-label-needed, approved

#5 Add halo-plugin-email
  README.md
Labels: lgtm, release-note-none, approved

#4 add plugin-lazyload
  README.md
Labels: lgtm, release-note-none, approved

#6 add plugin-tocbot
  README.md
Labels: lgtm, release-note-none, approved
