Repository halo-sigs/awesome-halo, pull requests merged in 2024-06, with the labels that each got.

#93 add plugin plugin-picture-bed
  README.md
Labels: lgtm, release-note-none, approved

#99 add halo-theme-twentytwelve
  README.md
Labels: lgtm, release-note-none, approved

#98 Add theme halo-theme-hingle2.0
  README.md
Labels: lgtm, release-note-none, approved

#96 add halo-theme-hellopage
  README.md
Labels: lgtm, release-note-none, approved

#100 新增插件plugin-artalk
  README.md
Labels: lgtm, release-note-none, approved

#101 add theme-Mego
  README.md
Labels: lgtm, release-note-none, approved

#106 update halo-plugin-typecho's repo
  README.md
Labels: lgtm, do-not-merge/release-note-label-needed, approved

#105 Add halo-plugin-postchat
  README.md
Labels: lgtm, release-note-none, approved

#103 Add plugin-editor-hyperlink-card
  README.md
Labels: release-note-none, approved
